[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'

[phases.setup]
    aptPkgs = [
        '...',
        'libnss3',
        'libatk1.0-0',
        'libatk-bridge2.0-0',
        'libcups2',
        'libgbm1',
        'libasound2',
        'libpangocairo-1.0-0',
        'libxss1',
        'libgtk-3-0',
        'libxshmfence1',
        'libglu1',
    ]
